/*
 * WARNING: RECREATING SQL SCHEMA COULD CAUSE DATA LOSS.
 *          PLEASE USE THIS FILE EXTREMELY CAREFULLY.
 */

DROP TABLE IF EXISTS 'URLs';

CREATE TABLE 'URLs' (
	`slug`		VARCHAR(16)	NOT NULL UNIQUE PRIMARY KEY,
	`destination`	VARCHAR(2048)	NOT NULL,
	`timestamp`	TIMESTAMP	NOT NULL DEFAULT CURRENT_TIMESTAMP
);
